// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"fmt"
	substrate3 "github.com/benjaminpina/galatea/internal/adapters/handlers/fiber/substrate"
	"github.com/benjaminpina/galatea/internal/adapters/repositories/sqlite"
	"github.com/benjaminpina/galatea/internal/config"
	"github.com/benjaminpina/galatea/internal/core/ports/substrate"
	substrate2 "github.com/benjaminpina/galatea/internal/core/services/substrate"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	recover2 "github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/google/wire"
	"log"
)

// Injectors from wire.go:

// InitializeAPI initializes the API application with all its dependencies
func InitializeAPI() (*Application, error) {
	app := ProvideFiberApp()
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	database, err := ProvideDatabase(config)
	if err != nil {
		return nil, err
	}
	substrateRepository := ProvideSubstrateRepository(database)
	substrateServiceImpl := ProvideSubstrateService(substrateRepository)
	substrateHandler := ProvideSubstrateHandler(substrateServiceImpl)
	application := &Application{
		App:           app,
		Config:        config,
		Database:      database,
		SubstrateRepo: substrateRepository,
		SubstrateSvc:  substrateServiceImpl,
		SubstrateHdlr: substrateHandler,
	}
	return application, nil
}

// wire.go:

// DatabaseSet is the provider set for database connections
var DatabaseSet = wire.NewSet(
	ProvideDatabase,
)

// RepositorySet is the provider set for repositories
var RepositorySet = wire.NewSet(
	ProvideSubstrateRepository, wire.Bind(new(substrate.SubstrateRepository), new(*sqlite.SubstrateRepository)),
)

// ServiceSet is the provider set for services
var ServiceSet = wire.NewSet(
	ProvideSubstrateService, wire.Bind(new(substrate.SubstrateService), new(*substrate2.SubstrateServiceImpl)),
)

// HandlerSet is the provider set for handlers
var HandlerSet = wire.NewSet(
	ProvideSubstrateHandler,
)

// AppSet is the provider set for the Fiber application
var AppSet = wire.NewSet(
	ProvideFiberApp,
)

// Application represents the complete application with all its dependencies
type Application struct {
	App           *fiber.App
	Config        *config.Config
	Database      *sqlite.Database
	SubstrateRepo substrate.SubstrateRepository
	SubstrateSvc  substrate.SubstrateService
	SubstrateHdlr *substrate3.SubstrateHandler
}

// ProvideConfig provides the application configuration
func ProvideConfig() (*config.Config, error) {
	return config.LoadConfig()
}

// ProvideDatabase provides the database connection based on the configuration
func ProvideDatabase(cfg *config.Config) (*sqlite.Database, error) {
	switch cfg.DatabaseType {
	case "sqlite":
		return sqlite.InitializeDatabase()

	default:
		return nil, fmt.Errorf("unsupported database type: %s", cfg.DatabaseType)
	}
}

// ProvideSubstrateRepository provides the substrate repository
func ProvideSubstrateRepository(db *sqlite.Database) *sqlite.SubstrateRepository {
	return sqlite.NewSubstrateRepository(db)
}

// ProvideSubstrateService provides the substrate service
func ProvideSubstrateService(repo substrate.SubstrateRepository) *substrate2.SubstrateServiceImpl {
	return substrate2.NewSubstrateService(repo)
}

// ProvideSubstrateHandler provides the substrate handler
func ProvideSubstrateHandler(svc substrate.SubstrateService) *substrate3.SubstrateHandler {
	return substrate3.NewSubstrateHandler(svc)
}

// ProvideFiberApp provides the Fiber application
func ProvideFiberApp() *fiber.App {
	return fiber.New(fiber.Config{
		AppName: "Galatea API",
		ErrorHandler: func(c *fiber.Ctx, err error) error {

			code := fiber.StatusInternalServerError

			if e, ok := err.(*fiber.Error); ok {
				code = e.Code
			}

			return c.Status(code).JSON(fiber.Map{
				"error": err.Error(),
			})
		},
	})
}

// SetupAPI configures the API application after initialization
func SetupAPI(app *Application) error {

	app.App.Use(logger.New())
	app.App.Use(recover2.New())
	app.App.Use(cors.New())

	app.SubstrateHdlr.RegisterRoutes(app.App)

	app.App.Get("/health", func(c *fiber.Ctx) error {
		return c.Status(fiber.StatusOK).JSON(fiber.Map{
			"status":   "ok",
			"database": app.Config.DatabaseType,
		})
	})
	log.Printf("API configured with database type: %s", app.Config.DatabaseType)
	return nil
}
