/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentsMenu: typeof import('./src/components/AgentsMenu.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    EnvironmentsMenu: typeof import('./src/components/EnvironmentsMenu.vue')['default']
    MainToolbar: typeof import('./src/components/MainToolbar.vue')['default']
    ProjectsMenu: typeof import('./src/components/ProjectsMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StagesMenu: typeof import('./src/components/StagesMenu.vue')['default']
    SubstratesMenu: typeof import('./src/components/SubstratesMenu.vue')['default']
  }
}
