// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSubstrateToMix(arg1, arg2) {
  return window['go']['main']['App']['AddSubstrateToMix'](arg1, arg2);
}

export function CreateMixedSubstrate(arg1) {
  return window['go']['main']['App']['CreateMixedSubstrate'](arg1);
}

export function CreateSubstrate(arg1) {
  return window['go']['main']['App']['CreateSubstrate'](arg1);
}

export function CreateSubstrateSet(arg1) {
  return window['go']['main']['App']['CreateSubstrateSet'](arg1);
}

export function DeleteMixedSubstrate(arg1) {
  return window['go']['main']['App']['DeleteMixedSubstrate'](arg1);
}

export function DeleteSubstrate(arg1) {
  return window['go']['main']['App']['DeleteSubstrate'](arg1);
}

export function DeleteSubstrateSet(arg1) {
  return window['go']['main']['App']['DeleteSubstrateSet'](arg1);
}

export function FindMixedSubstratesBySubstrateID(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindMixedSubstratesBySubstrateID'](arg1, arg2, arg3);
}

export function GetMixedSubstrate(arg1) {
  return window['go']['main']['App']['GetMixedSubstrate'](arg1);
}

export function GetSubstrate(arg1) {
  return window['go']['main']['App']['GetSubstrate'](arg1);
}

export function GetSubstrateSet(arg1) {
  return window['go']['main']['App']['GetSubstrateSet'](arg1);
}

export function ListMixedSubstrates(arg1, arg2) {
  return window['go']['main']['App']['ListMixedSubstrates'](arg1, arg2);
}

export function ListSubstrateSets(arg1, arg2) {
  return window['go']['main']['App']['ListSubstrateSets'](arg1, arg2);
}

export function ListSubstrates(arg1, arg2) {
  return window['go']['main']['App']['ListSubstrates'](arg1, arg2);
}

export function RemoveSubstrateFromMix(arg1, arg2) {
  return window['go']['main']['App']['RemoveSubstrateFromMix'](arg1, arg2);
}

export function UpdateMixedSubstrate(arg1, arg2) {
  return window['go']['main']['App']['UpdateMixedSubstrate'](arg1, arg2);
}

export function UpdateSubstrate(arg1, arg2) {
  return window['go']['main']['App']['UpdateSubstrate'](arg1, arg2);
}

export function UpdateSubstratePercentage(arg1, arg2) {
  return window['go']['main']['App']['UpdateSubstratePercentage'](arg1, arg2);
}

export function UpdateSubstrateSet(arg1, arg2) {
  return window['go']['main']['App']['UpdateSubstrateSet'](arg1, arg2);
}
