// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {substrate} from '../models';

export function AddSubstrateToMix(arg1:string,arg2:substrate.SubstratePercentageRequest):Promise<substrate.MixedSubstrateResponse>;

export function CreateMixedSubstrate(arg1:substrate.MixedSubstrateRequest):Promise<substrate.MixedSubstrateResponse>;

export function CreateSubstrate(arg1:substrate.SubstrateRequest):Promise<substrate.SubstrateResponse>;

export function CreateSubstrateSet(arg1:substrate.SubstrateSetRequest):Promise<substrate.SubstrateSetResponse>;

export function DeleteMixedSubstrate(arg1:string):Promise<void>;

export function DeleteSubstrate(arg1:string):Promise<void>;

export function DeleteSubstrateSet(arg1:string):Promise<void>;

export function GetMixedSubstrate(arg1:string):Promise<substrate.MixedSubstrateResponse>;

export function GetSubstrate(arg1:string):Promise<substrate.SubstrateResponse>;

export function GetSubstrateSet(arg1:string):Promise<substrate.SubstrateSetResponse>;

export function ListMixedSubstrates():Promise<Array<substrate.MixedSubstrateResponse>>;

export function ListSubstrateSets():Promise<Array<substrate.SubstrateSetResponse>>;

export function ListSubstrates():Promise<Array<substrate.SubstrateResponse>>;

export function RemoveSubstrateFromMix(arg1:string,arg2:string):Promise<substrate.MixedSubstrateResponse>;

export function UpdateMixedSubstrate(arg1:string,arg2:substrate.MixedSubstrateRequest):Promise<substrate.MixedSubstrateResponse>;

export function UpdateSubstrate(arg1:string,arg2:substrate.SubstrateRequest):Promise<substrate.SubstrateResponse>;

export function UpdateSubstratePercentage(arg1:string,arg2:substrate.SubstratePercentageRequest):Promise<substrate.MixedSubstrateResponse>;

export function UpdateSubstrateSet(arg1:string,arg2:substrate.SubstrateSetRequest):Promise<substrate.SubstrateSetResponse>;
