// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportMixedSubstrate(arg1, arg2) {
  return window['go']['main']['MixedSubstrateFileOperations']['ExportMixedSubstrate'](arg1, arg2);
}

export function ImportMixedSubstrate(arg1) {
  return window['go']['main']['MixedSubstrateFileOperations']['ImportMixedSubstrate'](arg1);
}
