// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {substrate} from '../models';

export function ExportMixedSubstrate(arg1:string,arg2:string):Promise<void>;

export function ImportMixedSubstrate(arg1:string):Promise<substrate.MixedSubstrateResponse>;
