// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSubstrateToMix(arg1, arg2) {
  return window['go']['main']['MixedSubstrateCRUD']['AddSubstrateToMix'](arg1, arg2);
}

export function CreateMixedSubstrate(arg1) {
  return window['go']['main']['MixedSubstrateCRUD']['CreateMixedSubstrate'](arg1);
}

export function DeleteMixedSubstrate(arg1) {
  return window['go']['main']['MixedSubstrateCRUD']['DeleteMixedSubstrate'](arg1);
}

export function FindMixedSubstratesBySubstrateID(arg1, arg2, arg3) {
  return window['go']['main']['MixedSubstrateCRUD']['FindMixedSubstratesBySubstrateID'](arg1, arg2, arg3);
}

export function GetMixedSubstrate(arg1) {
  return window['go']['main']['MixedSubstrateCRUD']['GetMixedSubstrate'](arg1);
}

export function ListMixedSubstrates(arg1, arg2) {
  return window['go']['main']['MixedSubstrateCRUD']['ListMixedSubstrates'](arg1, arg2);
}

export function RemoveSubstrateFromMix(arg1, arg2) {
  return window['go']['main']['MixedSubstrateCRUD']['RemoveSubstrateFromMix'](arg1, arg2);
}

export function UpdateMixedSubstrate(arg1, arg2) {
  return window['go']['main']['MixedSubstrateCRUD']['UpdateMixedSubstrate'](arg1, arg2);
}

export function UpdateSubstratePercentage(arg1, arg2) {
  return window['go']['main']['MixedSubstrateCRUD']['UpdateSubstratePercentage'](arg1, arg2);
}
