// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {substrate} from '../models';

export function AddSubstrateToMix(arg1:string,arg2:substrate.SubstratePercentageRequest):Promise<substrate.MixedSubstrateResponse>;

export function CreateMixedSubstrate(arg1:substrate.MixedSubstrateRequest):Promise<substrate.MixedSubstrateResponse>;

export function DeleteMixedSubstrate(arg1:string):Promise<void>;

export function FindMixedSubstratesBySubstrateID(arg1:string,arg2:number,arg3:number):Promise<substrate.MixedSubstratePaginatedResponse>;

export function GetMixedSubstrate(arg1:string):Promise<substrate.MixedSubstrateResponse>;

export function ListMixedSubstrates(arg1:number,arg2:number):Promise<substrate.MixedSubstratePaginatedResponse>;

export function RemoveSubstrateFromMix(arg1:string,arg2:string):Promise<substrate.MixedSubstrateResponse>;

export function UpdateMixedSubstrate(arg1:string,arg2:substrate.MixedSubstrateRequest):Promise<substrate.MixedSubstrateResponse>;

export function UpdateSubstratePercentage(arg1:string,arg2:substrate.SubstratePercentageRequest):Promise<substrate.MixedSubstrateResponse>;
