// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSubstrate(arg1) {
  return window['go']['main']['SubstrateCRUD']['CreateSubstrate'](arg1);
}

export function DeleteSubstrate(arg1) {
  return window['go']['main']['SubstrateCRUD']['DeleteSubstrate'](arg1);
}

export function GetSubstrate(arg1) {
  return window['go']['main']['SubstrateCRUD']['GetSubstrate'](arg1);
}

export function ListSubstrates(arg1, arg2) {
  return window['go']['main']['SubstrateCRUD']['ListSubstrates'](arg1, arg2);
}

export function UpdateSubstrate(arg1, arg2) {
  return window['go']['main']['SubstrateCRUD']['UpdateSubstrate'](arg1, arg2);
}
