// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSubstrateSet(arg1) {
  return window['go']['main']['SubstrateSetCRUD']['CreateSubstrateSet'](arg1);
}

export function DeleteSubstrateSet(arg1) {
  return window['go']['main']['SubstrateSetCRUD']['DeleteSubstrateSet'](arg1);
}

export function GetSubstrateSet(arg1) {
  return window['go']['main']['SubstrateSetCRUD']['GetSubstrateSet'](arg1);
}

export function ListSubstrateSets(arg1, arg2) {
  return window['go']['main']['SubstrateSetCRUD']['ListSubstrateSets'](arg1, arg2);
}

export function UpdateSubstrateSet(arg1, arg2) {
  return window['go']['main']['SubstrateSetCRUD']['UpdateSubstrateSet'](arg1, arg2);
}
