// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {substrate} from '../models';

export function ExportSubstrateSet(arg1:string,arg2:string):Promise<void>;

export function ImportSubstrateSet(arg1:string):Promise<substrate.SubstrateSetResponse>;
