// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {substrate} from '../models';

export function ExportSubstrate(arg1:string,arg2:string):Promise<void>;

export function ImportSubstrate(arg1:string):Promise<substrate.SubstrateResponse>;
