// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportSubstrate(arg1, arg2) {
  return window['go']['main']['SubstrateFileOperations']['ExportSubstrate'](arg1, arg2);
}

export function ImportSubstrate(arg1) {
  return window['go']['main']['SubstrateFileOperations']['ImportSubstrate'](arg1);
}
