// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {substrate} from '../models';

export function CreateSubstrateSet(arg1:substrate.SubstrateSetRequest):Promise<substrate.SubstrateSetResponse>;

export function DeleteSubstrateSet(arg1:string):Promise<void>;

export function GetSubstrateSet(arg1:string):Promise<substrate.SubstrateSetResponse>;

export function ListSubstrateSets(arg1:number,arg2:number):Promise<substrate.SubstrateSetPaginatedResponse>;

export function UpdateSubstrateSet(arg1:string,arg2:substrate.SubstrateSetRequest):Promise<substrate.SubstrateSetResponse>;
