// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportSubstrateSet(arg1, arg2) {
  return window['go']['main']['SubstrateSetFileOperations']['ExportSubstrateSet'](arg1, arg2);
}

export function ImportSubstrateSet(arg1) {
  return window['go']['main']['SubstrateSetFileOperations']['ImportSubstrateSet'](arg1);
}
